- hosts: master
  become: yes
  tasks:
    - name: initialization
      shell: kubeadm init --pod-network-cidr=172.16.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: creating .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copying admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: installing Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/anuraagrijal3138/calico_connfig/master/calico.yaml>> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
